name: Last run

on: [push]

jobs:
  check_log:
    runs-on: ubuntu-latest
    if: startsWith(github.event.head_commit.message, 'new result')
    steps:      
      - uses: actions/checkout@v2
      - run: |
          COMMIT=$(echo "${{ github.event.head_commit.message }}" | cut -d "[" -f2 | cut -d "]" -f1)
          FAIL=$(tail -1 logs/log_$COMMIT)
          if [[ "$FAIL" == "FAIL" ]]; then
              echo "The benchmark of commit $COMMIT failed. Look at logs/log_$COMMIT."
              exit 1
          fi
